name: Generate and Update Changelog.md
on: workflow_dispatch
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Import Utils
        run: |
          source ./devops/scripts/utils.bash
          source ./devops/scripts/release_utils.bash
      - name: Create Pull requests
        run: |
          RELEASE_VERSION=$(get_release_version)
          RELEASE_BRANCH_NAME=release/${RELEASE_VERSION}
          git checkout -b RELEASE_BRANCH_NAME
          append_changelog_text
          stage_and_commit_release_files 
          gh pr create -H ${RELEASE_BRANCH_NAME} --title "build: ${RELEASE_VERSION}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
